### ISSUE TITLE
Documentation / usage?

### ISSUE THREAD

**Issue by fr3fou** [woltapp/blurhash#1]
I couldn't find any documentation for the TypeScript usage. Do I really have to look through the `demo/` directory and look at the code? Is there any plan to have a wiki or anything similar? Great project btw! :>

**Comment by nygardk** [comment]
Blurhash TypeScript documentation coming soon 👍 !

**Comment by szepeviktor** [comment]
Thank you.

Could you please distribute the JavaScript decoder?

**Comment by fluffy-critter** [comment]
I would also love to use this in one of my projects, and would love to have a drop-in Javascript library I can just include to do the decoding.

**Comment by nygardk** [comment]
Javascript docs now available [here](https://github.com/woltapp/blurhash/tree/master/TypeScript).

**Comment by JamoCA** [comment]
The javascript docs references a `demo.js` file in the `/TypeScript/demo/index.html` file.  Where is the js file?
