### ISSUE TITLE
Horrible showcase

### ISSUE THREAD

**Issue by hfossli** [woltapp/blurhash#104]
Recorded on iPhone 11 Pro

https://user-images.githubusercontent.com/3652587/105367559-d9dfa480-5c00-11eb-9580-cb1cee3dd99f.MP4

Why all the flickering? I hope this isn't a concern I should have about this?

**Comment by codeclown** [comment]
> Horrible showcase

Could use a more descriptive and/or constructive title.

What does it look like stationary, without scrolling? I doubt the flickering has anything to do with blurhash functionality, just the scroll-dependent layout which seems to bug out.

**Comment by hfossli** [comment]
Exactly :) Shame to give bad impressions if this is not a problem. I don't know the reason and I hope, as you, it is not related to blurhas, but is due to bad layout approach.

**Comment by hfossli** [comment]
The flickering comes only when scrolling

**Comment by jerry-git** [comment]
I believe this is not really BlurHash related 🙂
