### ISSUE TITLE
Width and height must match the pixels array

### ISSUE THREAD

**Issue by ardyfeb** [woltapp/blurhash#107]
Error `Width and height must match the pixels array` when encoding blurhash with typescript(nodejs)

Implementation
```ts
const [buffer, metadata] = await fetchBuffer()

const clampedBuffer = new Uint8ClampedArray(buffer)
const encoded = encodeBlurhash(
   clampedBuffer,
   metadata.width,
   metadata.height,
   4,
   4
)
```

Inside `metadata`
```ts
{ format: 'jpeg', 
     size: 31912, 
     width: 400, 
     height: 500, 
     space: 'srgb', 
     channels: 3, 
     depth: 'uchar', 
     density: 72, 
     chromaSubsampling: '4:2:0', 
     isProgressive: true, 
     hasProfile: true, 
     hasAlpha: false, 
     icc: <Buffer 00 00 0c 48 4c 69 6e 6f 02 10 00 00 6d 6e 74 72 52 47 42 20 58 59 5a 20 07 ce 00 02 00 09 00 06 00 31 00 00 61 63 73 70 4d 53 46 54 00 00 00 00 49 45 ... 3094 more bytes> } } 
``` 

fetchBuffer()
```ts
function fetchBuffer(): Promise<[Buffer, Record<string, any>]> {
  const options: http.RequestOptions = {
    host: 'images.unsplash.com', 
    path: '/photo-1612383228565-d7423a28bdd7?auto=format&fit=crop&w=400'
  }

  const promises = new Promise<[Buffer, Record<string, any>]>(
    resolve => {
      const chunks = []
      const callback = (response: http.IncomingMessage): void => {
        response.on('data', data => chunks.push(data))
        response.on('end', () => {
          const buffer = Buffer.concat(chunks)

          sharp(buffer).metadata().then(
            info => resolve([buffer, info])
          )
        })
      }

      http.request(options, callback).end()
    }
  )

  return promises
}
```

**Comment by sunknudsen** [comment]
Hey @ardyfeb, would you mind sharing boilerplate code of how you managed to get this working on Node.js?

**Comment by ardyfeb** [comment]
@sunknudsen Sure, here the code

We need fetch raw data (to read pixels of image)
```ts
const { data: pixels, info: metadata } = await sharp(buffer).raw().toBuffer(
  { resolveWithObject: true }
)

const clamped = new Uint8ClampedArray(pixels)
const encoded = encodeBlurhash(
  clamped,
  metadata.width,
  metadata.height,
  4,
  4
)

console.log('blurhash', encoded)
```

**Comment by sunknudsen** [comment]
Thanks @ardyfeb!

I had just stumbled upon https://github.com/woltapp/blurhash/issues/43#issuecomment-597674435 which also helped.

**Comment by molomby** [comment]
I was getting this error when using the TypeScript implementation. It would occur when reading the image (a jpeg) directly off the disk (using `fs`) or with `sharp.raw()`. I was able to fix it by replacing `sharp(path).raw()` with `sharp(path).raw().ensureAlpha()`.

I don't know enough about image encoding to really tell whats happening but, looking at [the conditions that trigger this error](https://github.com/woltapp/blurhash/blob/master/TypeScript/src/encode.ts#L77), it seems the encode function is expecting 4 bytes per pixel:

```js
if (width * height * 4 !== pixels.length) {
   throw new ValidationError("Width and height must match the pixels array");
}
```

Presumably that bakes in an expectation that the alpha channel is present.

Fyi, [sharp.ensureAlpha() docs](https://sharp.pixelplumbing.com/api-channel#ensurealpha).

**Comment by mrousavy** [comment]
> it seems the encode function is expecting 4 bytes per pixel

But blurhash replaces alpha with black anyways, isn't that a waysted byte per pixel? 🤨

**Comment by houdayec** [comment]
Thanks @molomby for your answer!

However, I might be wrong, but as @mrousavy  says, it is a waste to save the alpha channel when it is not needed. For instance, on .jpg images, we do have only 3 channels (RGB), which is enough, no need to keep the alpha. It might be great to be able to indicate the number of channels of the image in the `encode` method.

**Comment by briosheje** [comment]
> I was getting this error when using the TypeScript implementation. It would occur when reading the image (a jpeg) directly off the disk (using `fs`) or with `sharp.raw()`. I was able to fix it by replacing `sharp(path).raw()` with `sharp(path).raw().ensureAlpha()`.
> 
> I don't know enough about image encoding to be sure but, looking at [the conditions that trigger this error](https://github.com/woltapp/blurhash/blob/master/TypeScript/src/encode.ts#L77), it seems the encode function is expecting 4 bytes per pixel:
> 
> ```js
> if (width * height * 4 !== pixels.length) {
>    throw new ValidationError("Width and height must match the pixels array");
> }
> ```
> 
> So red, green, blue and alpha.
> 
> Fyi, [sharp.ensureAlpha() docs](https://sharp.pixelplumbing.com/api-channel#ensurealpha).

Although this solution works, in my test cases it took a whole lot more than without `ensureAlpha`.

Is it currently the only feasible solution to avoid the issue?

**Comment by ashkan-esz** [comment]
> I was getting this error when using the TypeScript implementation. It would occur when reading the image (a jpeg) directly off the disk (using `fs`) or with `sharp.raw()`. I was able to fix it by replacing `sharp(path).raw()` with `sharp(path).raw().ensureAlpha()`.
> 
> I don't know enough about image encoding to be sure but, looking at [the conditions that trigger this error](https://github.com/woltapp/blurhash/blob/master/TypeScript/src/encode.ts#L77), it seems the encode function is expecting 4 bytes per pixel:
> 
> ```js
> if (width * height * 4 !== pixels.length) {
>    throw new ValidationError("Width and height must match the pixels array");
> }
> ```
> 
> So red, green, blue and alpha.
> 
> Fyi, [sharp.ensureAlpha() docs](https://sharp.pixelplumbing.com/api-channel#ensurealpha).

tnx for the answer, dont forget .toBuffer() after .raw()  for me it was needed.

**Comment by guest271314** [comment]
`ImageData` works

```
var pngRequest = await fetch(
  import.meta.resolve(
    "https://deno.com/blog/build-image-resizing-api/cover.png",
  ),
);

var pngBuffer = await pngRequest.arrayBuffer();

console.log(pngRequest.url.split("/").pop());

var { width: pngWidth, height: pngHeight } = getImagePixelDimensions(
  pngBuffer,
  "png",
);

console.assert((pngWidth === 2000) && (pngHeight === 1048), {
  pngWidth,
  pngHeight,
});

console.log({ pngWidth, pngHeight });

var pngClamped = new Uint8ClampedArray(pngBuffer);
pngImageData.data.set(pngClamped);

try {
  var pngHash = blurhash.encode(pngImageData.data, pngWidth, pngHeight, 4, 4);
  console.log({ pngHash });
} catch (e) {
  console.error(e);
}
```
