### ISSUE TITLE
Xojo implementation

### ISSUE THREAD

**Issue by piradoiv** [woltapp/blurhash#143]
Hi!, loved the idea so I've implemented in Xojo language:
https://github.com/piradoiv/xojo-blurhash

**Comment by jerry-git** [comment]
Hi! If you'd like to have this mentioned in the readme, could you provide a PR? 🙂

**Comment by piradoiv** [comment]
Sure Jerry, I'll be happy to prepare it =)

**Comment by piradoiv** [comment]
Here it is, thank you!
https://github.com/woltapp/blurhash/pull/175

**Comment by piradoiv** [comment]
Thank you for merging it!
