### ISSUE TITLE
It takes really long in typescript

### ISSUE THREAD

**Issue by krystofex** [woltapp/blurhash#153]
- for quad HD image blurhash generation takes about 30 seconds

I don't know if it's just my specific problem, but I have four larger images (6000 x 4000), I convert them to a max of 2560px on one side, and it takes about two minutes to generate a 6 x 6 blurhash for all of them. If I convert them to a max of 256px on one side, it takes almost no time at all, which makes sense, but the two minutes seems too much even for such a large image. Maybe would help some downscaling before generating blurhash.

**Comment by iliser** [comment]
Huh, unlucky but TS/JS too slow for this kind of algorithms. It's too many operations over numbers and data access in it. So JS and JIT compiler just can't handle it properly. Also implementation of algorithm is kinda suck, simple reorder of loops get it x2-5  faster. 

So for generation i prefer to use C version and call it through exec. In end cause C version is realy slow too i add tons of low level optimization and rewrite it to c++. If intresting you can check it [here](https://github.com/iliser/optimized_blurhash_encoder ), [plain c version with all optimizations](https://github.com/iliser/optimized_blurhash_encoder/tree/c_version)

**Comment by caiokf** [comment]
I have the same problem, what I do is resize the image down first

**Comment by predaytor** [comment]
I ran some tests and chose 32x32 for output to put in base64, creating hash from 64x64 of the original image. Run pretty fast on multiple images at once.

**Comment by Thisen** [comment]
It's already been mentioned, but there's a couple of things:
- JS is not the fastest at such computations
- You should resize the image down

Good question though :)
