### ISSUE TITLE
Different hashes for same picture

### ISSUE THREAD

**Issue by vanniktech** [woltapp/blurhash#196]
When using `4x3` on the website with the given [image](https://blurha.sh/12c2aca29ea896a628be.jpg), I get:

<img width="1247" alt="Screen Shot 2022-09-09 at 14 09 25" src="https://user-images.githubusercontent.com/5759366/189346862-73e096c8-bff4-403d-aa0a-f751308c3a02.png">

```
LEHV6nWB2yk8pyo0adR*.7kCMdnj
```

When I clone the repository, execute `yarn run demo` and test the Typescript library with the exact same image using `4x3`, I get:

<img width="1728" alt="Screen Shot 2022-09-09 at 14 10 20" src="https://user-images.githubusercontent.com/5759366/189347026-e6451ecd-b0cc-4b15-a8a1-50b105482a43.png">

```
LEHLh[jZ2ykUpyoKadR*.8kCMdnj
```

The strings are similar, but why aren't they exactly the same?

**Comment by vanniktech** [comment]
I've also taken the pictures from Python and ran them through localhost and the blurhashes in the Python tests are also different from Typescript.

**Comment by Thisen** [comment]
There'll be variations based on the environment - Environment could be browser, Node.js, Python or other languages. This difference is OK and expected, as a blurhash is an approximation.
