### ISSUE TITLE
Where is the Changelog

### ISSUE THREAD

**Issue by lionep** [woltapp/blurhash#213]
Hello,

I'm currently using blurhash v1.1.5 in a nodejs backend, and there is an available update to 2.0.3.  
I don't find any changelog or any migrating instructions. Are there any breaking change upgrading from v1 to v2 ?

Thanks !

**Comment by Thisen** [comment]
The changelog is here: https://docs.rs/dtolnay/latest/dtolnay/index.html#

The last patch release for `2.x` has been various fixes to bundling.

**Comment by lionep** [comment]
Is it the right project ? I don't see any blurhash reference in the link you provide.
