### ISSUE TITLE
Blurhashes on Roku

### ISSUE THREAD

**Issue by sevenrats** [woltapp/blurhash#222]
Good day!
I have implemented a variation of your algorithm for the Roku.  It is currently available on npm as fake-blurhash and I wanted to offer you the opportunity to look at the project and be heard if you feel it intrudes on your intellectual property.  Thanks.
https://github.com/sevenrats/fake-blurhash-roku

**Comment by Thisen** [comment]
All good! Please add it to our list of Open source implementations :)
