### ISSUE TITLE
Decode produces massive image in dimensions

### ISSUE THREAD

**Issue by ivanjaros** [woltapp/blurhash#225]
The example to decode the image produces image that is 300x150px instead of 32x32px for some reason. Any idea why?

```
   if (isBlurhashValid(hash) === false) {
      return ""
    }
    const pixels = decode(hash, 32, 32);
    const canvas = document.createElement("canvas");
    const ctx = canvas.getContext("2d");
    const imageData = ctx.createImageData(32, 32);
    imageData.data.set(pixels);
    ctx.putImageData(imageData, 0, 0);
    return canvas.toDataURL('image/jpeg', 1)
```

![obrázok](https://user-images.githubusercontent.com/64546059/203053331-f99fba6b-831d-4e23-8f51-ef6930c7e707.png)

**Comment by Thisen** [comment]
Could you try to set the canvas' width and height to match the width and height you want?

If that doesn't work, please provide a Codesandbox or Stackblitz reproduction.

**Comment by ivanjaros** [comment]
```
canvas.width = 32;
canvas.height = 32;
```
worked. i though the `const imageData = ctx.createImageData(32, 32); `will handle this.
