### ISSUE TITLE
Which implementation of BlurHash is most suitable for embeding in to Google Cloud Functions for encoding an Image?

### ISSUE THREAD

**Issue by aytunch** [woltapp/blurhash#39]
Thanks for this game changer algorithm/tool.

I need to use back-end encoding since there are no encoding libraries for dart/flutter yet. And people recommend against encoding in mobile client. 

I use google back-end and after some investigation [I found out that Python code can be run from Google Cloud Functions.](https://cloud.google.com/functions/docs/quickstart-python#create_a_function)

There is a Pure Python implementation and there is one which is not pure Python(It uses C code). Are these two compatible with GCF?

If not, which language implemantation can we embed in GCF? Typescript? Javascript? C? etc..

I want to make a HTTP request function in Cloud Functions which will run one of these implementation libraries and encode an Image and return a blurhash string. 

Thanks

**Comment by freitzzz** [comment]
> Thanks for this game changer algorithm/tool.
> 
> I need to use back-end encoding since there are no encoding libraries for dart/flutter yet. And people recommend against encoding in mobile client.
> 
> I use google back-end and after some investigation [I found out that Python code can be run from Google Cloud Functions.](https://cloud.google.com/functions/docs/quickstart-python#create_a_function)
> 
> There is a Pure Python implementation and there is one which is not pure Python(It uses C code). Are these two compatible with GCF?
> 
> If not, which language implemantation can we embed in GCF? Typescript? Javascript? C? etc..
> 
> I want to make a HTTP request function in Cloud Functions which will run one of these implementation libraries and encode an Image and return a blurhash string.
> 
> Thanks

There is already implementations of the encoder & decoder as a pure dart package (can run on server-side) and also Flutter, but I don't really see the use case to use the encoder in your Flutter app.

Pure dart: https://github.com/justacid/blurhash-daracct (I vouch this one)
Implementation with a Flutter Material widget: https://github.com/Solido/Flutter-BlurHash

**Comment by aytunch** [comment]
@freitzzz thanks for sharing this new Dart implementation which has both decode/encode. I will be trying it asap.

> but I don't really see the use case to use the encoder in your Flutter app.

I was thinking of encoding the image which I am about to upload to Firestore and upload the BlurHash string along with the image. Do you think this strategy is bad? I am in a fact distrubuting the load to clients. Also uploading an image does not happen too often. Furthermore, I can create the BlurHash from a downsized version of the image to increase performance. What do you think?

**Comment by freitzzz** [comment]
> @freitzzz thanks for sharing this new Dart implementation which has both decode/encode. I will be trying it asap.
> 
> > but I don't really see the use case to use the encoder in your Flutter app.
> 
> I was thinking of encoding the image which I am about to upload to Firestore and upload the BlurHash string along with the image. Do you think this strategy is bad? I am in a fact distributing the load to clients. Also uploading an image does not happen too often. Furthermore, I can create the BlurHash from a downsized version of the image to increase performance. What do you think?
> 
> And for the Google Cloud part of the question, what would be your strategy? Should we go with pure python implementation?

Oh I didn't think you needed to upload an image on your app, my bad. I was assuming you needed to serve the image as the common use case for blurhash is to display images from server-side that may have some latency to receive. I don't think distributing the load in the app and uploading the images to Firestore is a bad thing, in fact thats a very smart thing to do as you don't need to create an extra component to serve your images :) Just make sure the extra work on the app doesn't affect the user experience (e.g. frame rate loss)!!

Regarding the pure python implementation use, I'm not familiar or experienced with Google Cloud Functions so I cannot give you an opinion on that, sorry :( But Python is conceived to be part of the Google Stack, but if thats a problem, I'm pretty sure that there is a GCF SDK for Node.js in which you can integrate the Typescript implementation :D

**Comment by jerry-git** [comment]
Btw there seems to be a pure Python implementation in https://github.com/halcy/blurhash-python 🙂
