### ISSUE TITLE
Add link to pure JS implementation repo to readme

### ISSUE THREAD

**Issue by Dens49** [woltapp/blurhash#47]
Hey, I really like the project!

I couldn't find a vanilla JS version, only the TypeScript one, so I ported the TypeScript implementation to vanilla JS and added a helper function here and there.

The repo: https://github.com/Dens49/blurhash-js

If my repo holds up to your standards, you might want to consider adding a link to it to your Readme. I'm sure there are more people looking for a vanilla JS version.

**Comment by DagAgren** [comment]
Make a PR with the link.
