### ISSUE TITLE
Random hash 

### ISSUE THREAD

**Issue by dfdgsdfg** [woltapp/blurhash#48]
Can I have random hash not from image?

It can be useful from null or default case.

**Comment by DagAgren** [comment]
I have been experimenting with things in the Swift BlurHashKit project. Check out https://github.com/woltapp/blurhash/blob/master/Swift/BlurHashKit/Generation.swift for instance.

You could even just try using random AC components (probably with decreasing amplitude or something).

**Comment by StoneyEagle** [comment]
I took some of the source code and created a typescript function that suits my needs.
Works best with a 2x2.
https://gist.github.com/StoneyEagle/8a773f4ec60339bc59376476f1fe6b61
