### ISSUE TITLE
Decouple encoding from image processing algorithm

### ISSUE THREAD

**Issue by Tylerian** [woltapp/blurhash#53]
First of all, thank you for this wonderful algorithm, it's a game-changer.

I've read the algorithm code and noticed that currently the encoding is coupled inside the algorithm. I propose to decouple it, storing the raw encode/decode outputs on a byte array and then passing it to the encoding function of our choice.

I can even chime in and do a pull request if this idea gets approbation from you guys.

**Comment by DagAgren** [comment]
I'd suggest making your own custom implementation for this. The current one is tuned to be as compact as possible, which I think is desirable for most use cases. If you want a more advanced one, it should probably be separate.

For instance, there is already a much more advanced Swift implementation in the BlurHashKit directory.
