### ISSUE TITLE
Swift decoder is really slow!

### ISSUE THREAD

**Issue by mrousavy** [woltapp/blurhash#70]
The [Swift decoder](https://github.com/woltapp/blurhash/blob/master/Swift/BlurHashDecode.swift) is really slow compared to the [Android (Kotlin) decoder](https://github.com/woltapp/blurhash/blob/master/Kotlin/lib/src/main/java/com/wolt/blurhashkt/BlurHashDecoder.kt).

Here are some benchmarks I made while creating the [mrousavy/react-native-blurhash](https://github.com/mrousavy/react-native-blurhash) library:

<table>
  <tr>
    <th>Blurhash Size</th>
    <th>iOS</th>
    <th>Android</th>
  </tr>
  <tr>
    <td><b>32 x 32</b></td>
    <td><code>8</code> ms</td>
    <td><code>2</code> ms</td>
  </tr>
  <tr>
    <td><b>400 x 400</b></td>
    <td><code>1.134</code> ms</td>
    <td><code>130</code> ms</td>
  </tr>
  <tr>
    <td><b>2000 x 2000</b></td>
    <td><code>28.894</code>ms</td>
    <td><code>3.336</code>ms</td>
  </tr>
</table>

Of course you would never need such high decode widths/heights, this is just for benchmarking purposes. But even with 32x32 the iOS decoder is **4 times** slower than the Android one! This doesn't play out nicely in large lists, as two blurhashes already cause a framedrop (16ms = 1/60 fps).

After a lot of debugging I'm still not quite sure where the bottleneck is in the [Swift decoder](https://github.com/woltapp/blurhash/blob/master/Swift/BlurHashDecode.swift), does anyone have an idea/solution?

**Comment by DagAgren** [comment]
You should not decode anything more than 32x32. The additional resolution does not give you anything that scaling the image up doesn't already.

Just decode at 32x32, and let the UIImageView scale it up.

**Comment by mrousavy** [comment]
@DagAgren yes, that's what I said. It doesn't make sense to decode with higher values than 32. But this is a _benchmark_, which shows that the Swift encoder is slower than the Android encoder, even on smaller values such as 32 or 16 and those times will sum up. Let's say for example I were to use multiple Blurhashes in a ListView, that's what, 10 images at the same time? `10 * 8 = 80ms` of decoding, that's 5 dropped frames. A user will notice this.

I've currently came around this issue by decoding on a Background Thread, but performance optimizations are always a good option.

**Comment by DagAgren** [comment]
Is that with a release build? Calculation-heavy Swift code can be very slow in debug builds.
